# Generated by Django 4.2.3 on 2024-01-31 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_time_alter_game_created_alter_game_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
